"""Add indexes and email verification

Revision ID: 3454c73784b0
Revises: e7ae4fb1e69c
Create Date: 2026-08-28 01:47:21.674341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3454c73784b0'
down_revision: Union[str, Sequence[str], None] = 'e7ae4fb1e69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_raw_articles_fetched_at'), 'raw_articles', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_raw_articles_is_world'), 'raw_articles', ['is_world'], unique=False)
    op.create_index(op.f('ix_raw_articles_pakistan_score'), 'raw_articles', ['pakistan_score'], unique=False)
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('verification_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code_expires_at')
    op.drop_column('users', 'verification_code')
    op.drop_index(op.f('ix_raw_articles_pakistan_score'), table_name='raw_articles')
    op.drop_index(op.f('ix_raw_articles_is_world'), table_name='raw_articles')
    op.drop_index(op.f('ix_raw_articles_fetched_at'), table_name='raw_articles')
    # ### end Alembic commands ###
